name: Build LaTeX document
on:  
  push:
    tags:
      - '*'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      
      - name: Build LaTeX Document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            bash ./build.sh run_build
      
      - name: Create Artifacts of PDFs
        uses: actions/upload-artifact@v2
        with:
          name: Resume_PDF
          path: ./

      - name: Create a Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.pdf
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
