name: Build JSON Resume
on:
  push:
    paths:
      - "*.jsonc"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build Resume PDF
        run: |
          bash ./run run_build

      - name: Create Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Built-Resume
          path: ./out/*

      # Will only create a release, if pushed with tag
      - name: Create a Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            out/*.pdf
