name: Build LaTeX Resume
on:
  push:
    tags:
      - "*"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build LaTeX
      run: |
        bash ./run.sh run_build
    
    - name: Create a Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          out/**/*.pdf
      
    - name: Upload PDF to Google Drive
      uses: PeronTheDuck/glob-to-drive@v4
      with:
        glob: "out/**/*.pdf"
        keepStructure: false
        uploadTo: ${{ secrets.DRIVE_FOLDER_ID }}

        credentials: ${{ secrets.CREDENTIALS }}
        token: ${{ secrets.TOKEN }}
        mimeType: "application/pdf"
        
        